### ISSUE TITLE
Cucumber does not conform to protocol StepImplementation

### ISSUE THREAD

**Issue by azamsharp** [Tyler-Keith-Thompson/CucumberSwift#11]
I am following your docs and in the docs you implement Given, When and Then. I did the same but was greeted with the error "Type Cucumber does not conform to protocol StepImplementation". 

I have a Features folder which contain the following feature: 

Feature: Example

Scenario: First Scenario

    Given I have a very cool app
    When I type my name in the name text field
    Then I should see my name displayed in a label 

I have a Steps group with file "WeatherStepsImplementation.swift" which contains the following code. 

```
extension Cucumber: StepImplementation {
    
    public func setupSteps() {
        
        Given("I have a very cool app") { (matches, _) in
            print(matches)
        }
        
        When("I type my name in the name text field") { (matches, _) in
            print(matches)
        }
        
        Then("I should see my name displayed in a label ") { (matches, _) in
            print(matches)
            
        }
        
    }
}
```

**Comment by Tyler-Keith-Thompson** [comment]
Thanks for reaching out! I suspect somehow Xcode is not nicely autocompleting for you (lame). Try adding this required variable:

```swift
public var bundle: Bundle {
        return //your test bundle here. you can find it with a class like: Bundle(for: MyClass.self)
}
```

**Comment by azamsharp** [comment]
Still does not even compile. 

<img width="659" alt="Screen Shot 2020-04-13 at 3 33 37 PM" src="https://user-images.githubusercontent.com/16604/79158554-29ed2900-7d9c-11ea-9a01-ee2b53a67e7e.png">

**Comment by Tyler-Keith-Thompson** [comment]
So in that case it looks like you're giving it a module instead of a class. Try `Findme.self` instead of `WeatherCucumberSwiftTests.self` (which again, thinks it's referencing the name of the swift module)

**Comment by Tyler-Keith-Thompson** [comment]
I'm closing this as your actual issue seems to be [here](https://github.com/Tyler-Keith-Thompson/CucumberSwift/issues/13)
