### ISSUE TITLE
Warning shown in xCode 12.0.1

### ISSUE THREAD

**Issue by contractor-jim** [Tyler-Keith-Thompson/CucumberSwift#19]
**Describe the bug**
A very minor issue but happy to put into a PR if you want. But when compiling with the latest release of xCode there is a warning in CucumberSwift.swift file on line 20:

` _ = XCTContext.runActivity(named: "\(self.keyword.toString()) \(self.match)") { _ in`

The call to XCTContext.runActivity is now a void returning function which means that you can remove the leading  _ = 

**To Reproduce**
1. Build the pod on 12.0.1 version of xCode
2. Observe the below error: 

<img width="472" alt="Screenshot 2020-10-15 at 14 52 47" src="https://user-images.githubusercontent.com/47974377/96138837-18750d00-0ef6-11eb-9ef7-e8cb7f7deab2.png">

**Comment by Tyler-Keith-Thompson** [comment]
Thanks for bringing this up! It should be resolved as of CucumberSwift v3.0.9
