### ISSUE TITLE
Tags do not support colons

### ISSUE THREAD

**Issue by cody1024d** [Tyler-Keith-Thompson/CucumberSwift#26]
Hello (again)!

I've found a small issue ---

If, for example I have the below:

```
@launchPage:Consumer18_4
  Scenario: Valid load
    ....
```

The tags property on the Scenario object, only shows having a tag of "launchPage".  It seems to be leaving off the second part.

My use-case is, again from creating a framework point of view, I need the developers to be able to define extra meta-data about the scenario.  In this case, this tag is performing 2 steps which are extremely boiler-platey that nearly all scenarios will have.

Thanks,
Cody

**Comment by Tyler-Keith-Thompson** [comment]
Huh, you're right. I *thought* the official spec said tags were Alphanumeric but looking at the tests in the official cucumber repo it would appear `_` is a valid character. I need to do a little digging to try and see if there's a gherkin language spec that says how this is *supposed* to work, I also need to adapt my tests that use the official Cucumber "good" JSON to read tags.

I'll start working on this ASAP.

Do you happen to know off-hand if a tag is:
- A token starting with `@` and terminated by any whitespace character or another `@`
- A token starting with `@` and terminated by any character not in an "allowed" characters set (like '_', '-')
- Some other rule

I do know that `@tag1@tag2` with no whitespace *is* valid, I've got explicit tests for that in the repo.

**Comment by Tyler-Keith-Thompson** [comment]
Hrm also...where is the concrete object's property not working? Is it in a hook? In a step? Cause my first tests actually show this works as expected.

**Comment by cody1024d** [comment]
I'm not sure the exact grammar rules surrounding tags, unfortunately, although some tutorials I'm seeing online []((http://docs.eggplantsoftware.com/ePF/using/epf-advanced-gherkin.htm#tags)) seem to only mention white-space as invalid characters.

For more context on the current situation (if needed):

- It looks like both '-' and '_' actually are currently handled by the framework (based on my currently running code. I'm splitting the tag up to basically capture parts of it.  So in the above example, I'm currently using: @launchPage-Consumer18_4, to get a reference to the value Consumer18_4)
- The colon is definitely not working, although I'm not sure what other special characters are also not working.

**Comment by cody1024d** [comment]
Here are some useful links that I dug up, that may help.  I'm not seeing anything on a skim through, in the granularity of characters, but maybe you can find something: 

[Language Spec](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp)

Also, here is the gherkin repo, which has a ReadMe that may help as well:

[Gherkin Repo](https://github.com/cucumber/cucumber/tree/master/gherkin)

**Comment by Tyler-Keith-Thompson** [comment]
CucumberSwift 3.1.2 fixes this issue. I'll leave this open until you've had a chance to validate on your end

**Comment by cody1024d** [comment]
Confirmed working!  Thanks @Tyler-Keith-Thompson!  Closing this issue.
