### ISSUE TITLE
DataTable.rows is inaccessible due to internal protection level

### ISSUE THREAD

**Issue by albedinsky** [Tyler-Keith-Thompson/CucumberSwift#28]
**Describe the bug**

When trying to access `rows` property in `DataTable`, like `step.dataTable!.rows`, the compiler complains that this property is not accessible due to **internal protection level**.

When looking at `DataTable` implementation, the `rows` property is not actually **public**, maybe this is the problem?

According to [documentation](https://github.com/Tyler-Keith-Thompson/CucumberSwift/wiki/how-do-i-use-it) related to _Test Data_ this should be possible.

**To Reproduce**
1. Implement basic `When("^Step$") { maches, step in ... }` step definition
2. Try to access `step.dataTable!.rows` property
3. See error like the one attached

**Expected behavior**
The `rows` property on `DataTable` instance should be **accessible**.

**Screenshots**
<img width="1046" alt="Screenshot 2021-04-22 at 13 20 01" src="https://user-images.githubusercontent.com/3187996/115707613-4dfc2680-a36f-11eb-8eee-75b5170a2f1d.png">

**Additional context**
 - XCode Version: 12.4
 - CucumberSwift Version: 3.1.2

**Comment by Tyler-Keith-Thompson** [comment]
Wow! Can't believe that got missed. I've got a consumer test that does an `import` instead of a `@testable import` now to prevent this from happening again for this issue. I'm not at the computer that has my tokens to be able to deploy, but will get this fix released for you ASAP.

**Comment by albedinsky** [comment]
No problem @Tyler-Keith-Thompson, thank you :)

**Comment by Tyler-Keith-Thompson** [comment]
CucumberSwift 3.1.4 was just released and fixes this issue.
