### ISSUE TITLE
No error when a Gherkin statement doesn't match any CucumberSwift expressions

### ISSUE THREAD

**Issue by hkingverily** [Tyler-Keith-Thompson/CucumberSwift#36]
**Describe the bug**
No error when a Gherkin statement doesn't match any CucumberSwift expressions

**To Reproduce**
1. Add a Gherkin statement
2. No CucumberSwift expression that matches the Gherkin statement

**Expected behavior**
Error for Gherkin statement with no matching CucumberSwift expressions

**Additional context**
 - CucumberSwift Version: 3.3.6

**Comment by alexvoss** [comment]
Either a warning or an error on unmatched steps would be good. I am trying out CucumberSwift but am only getting `testGherkin()` in my test results. None of my scenarios run and I have nothing to go by as to why this might be the case. 

The process described for [generating step stubs](https://github.com/Tyler-Keith-Thompson/CucumberSwift/wiki/generated-step-stubs) does not seem to work. I had a quick look at the sources and there does not seem to be a class `GenerateStubsIfNecessary`? Has this functionality been dropped?

This is a shame as CucumberSwift seems to be the hottest contender for doing BDD in Swift.

**Comment by alexvoss** [comment]
Ok, my problem was that I did not have the Features directory added to the UITest Target. I assume CucumberSwift did not find any .feature files but passed `testGherkin()`?

**Comment by Tyler-Keith-Thompson** [comment]
> Ok, my problem was that I did not have the Features directory added to the UITest Target. I assume CucumberSwift did not find any .feature files but passed `testGherkin()`?

Yeah, in order to make it so that consumers had to do as little as possible CucumberSwift ships with a test called `testGherkin`. It actually uses execution of that test to do a variety of different tasks at runtime. 

Previous versions used ideas like `Principal Class` in the info.plist or a `+load()` method, but it all required consumers to do more.

**Comment by Tyler-Keith-Thompson** [comment]
However, many people have run into the issue of not having the features directory correctly added and I think there's a reasonable way CucumberSwift could report no feature files found. Let me add that to the todo along with this issue.

**Comment by alexvoss** [comment]
Thanks, great. Would it be possible to get something like a verbose output option? I have tests running but only some of them actually execute code. That is, I have a scenario outline and the expected tests are generated and appear in the test navigator but the step code is never executed, not even for the Given step. I set breakpoints to check and they did not get hit. I am sure I am making beginner mistakes somewhere - it would be good to be able to see what CucumberSwift is and is not doing.

**Comment by Tyler-Keith-Thompson** [comment]
To keep issues clearly separated I've created #41 and #42 to capture some of the ideas in here. Meanwhile the original point of this issue will be prioritized and addressed.

**Comment by Tyler-Keith-Thompson** [comment]
Adding this feature actually gave a MUCH better opportunity to give generated step stubs to consumers.

Here are some screenshots that showcase how it works
<img width="2431" alt="Screen Shot 2022-04-20 at 4 39 38 PM" src="https://user-images.githubusercontent.com/33705774/164336552-3f4edfdd-67c0-4522-ba2e-82938415caa3.png">
<img width="2431" alt="Screen Shot 2022-04-20 at 4 39 41 PM" src="https://user-images.githubusercontent.com/33705774/164336579-411bdb6a-2444-4b56-8c49-8bd425ebf9ea.png">

If consumers do not desire this behavior there's a somewhat undocumented swift feature they can use to disable it:
```swift
extension CucumberTest {
    @_dynamicReplacement(for: failStep)
    func replacementFailStep(_ issue: XCTIssue) { }
}
```

**Comment by Tyler-Keith-Thompson** [comment]
NOTE: This also works when giving you generated code for known types. In this case a doc string (notice the generated code shows you how to access that doc string)

<img width="2350" alt="Screen Shot 2022-04-20 at 4 42 50 PM" src="https://user-images.githubusercontent.com/33705774/164336761-0a924d37-2a37-4ed9-9211-22286d11f620.png">

**Comment by Tyler-Keith-Thompson** [comment]
Release in 3.3.10
