### ISSUE TITLE
Duplicate Symbols for each Test Case

### ISSUE THREAD

**Issue by DavidSiebecker** [Tyler-Keith-Thompson/CucumberSwift#38]
**Describe the bug**
When running CucumberSwift tests from feature files, the console output contains warnings about duplicate symbols. E.g.
objc[51303]: Class CucumberSwiftLibrary|BeforeFeatureHookWorksCorrectly is implemented in both ?? (0x100fe2ac0) and ?? (0x100fe3850). One of the two will be used. Which one is undefined.
objc[51303]: Class CucumberSwiftLibrary|BeforeFeatureHookWorksCorrectly is implemented in both ?? (0x100fe2ac0) and ?? (0x100fe4260). One of the two will be used. Which one is undefined.

**To Reproduce**
1. Clone the CucumberSwift repo
2. Run the test suites
3. Examine the output

**Expected behavior**
I would expect no duplicate symbols to be created.

**Screenshots**
N/A

**Additional context**
 - XCode Version: [e.g. XCode 13.2.1]
 - CucumberSwift Version: [e.g. 3.3.6]
 - Example Feature File: Files are included in the CucumberSwift Repo.

I took a look through the source code and found that this part

```
        let uniqueName = { () -> String in
            var count = 0
            var name = className
            while NSClassFromString(name) != nil {
                count += 1
                name = "\(name)\(count)"
            }
            return name
        }()
```
 of `TestCaseGenerator.swift` is supposed to protect against this but the classes aren't being registered in `CucumberTest.swift` until after all the test steps for the scenario have been run through. 
 
 ```
         scenario.steps.compactMap { step -> (step: Step, XCTestCase.Type, Selector)? in
            if let (testCase, methodSelector) = TestCaseGenerator.initWith(className: className.appending(scenario.title.toClassString()),
                                                                           method: step.method) {
                return (step, testCase, methodSelector)
            }
            return nil
        }
        .map { step, testCaseClass, methodSelector -> (Step, XCTestCase) in
            objc_registerClassPair(testCaseClass)
            return (step, testCaseClass.init(selector: methodSelector))
        }
```

Moving the `objc_registerClassPair` up to the `compactMap` solves the problem but then makes the test navigator output look weird.

**Comment by Tyler-Keith-Thompson** [comment]
Thank you for tracking down the exact spot this is happening. Using `.lazy` is an easy way to solve it.

**Comment by Tyler-Keith-Thompson** [comment]
v3.3.7 does fix this, but as you pointed out while it does generate unique names it has unexpected output.  Instead of `ConflictingName2` you get `ConflictingName12`. 

I'll consider the issue closed for now, but fix that uniquing function in a future release
