### ISSUE TITLE
Non-Latin characters in test names

### ISSUE THREAD

**Issue by alexvoss** [Tyler-Keith-Thompson/CucumberSwift#39]
**Describe the bug**
Non-Latin characters in the test navigator come out mangled.

**To Reproduce**
1. Write a feature file with non-Latin characters such as German umlaute in the text
2. Implement step definitions
3. Run tests
4. Look at list of tests in Xcode's test navigator

**Expected behavior**
Expected non-Latin characters to be preserved in the output. One of my steps is:
--8<--
Dann wird eine Begrüßung auf <Sprache> angezeigt
--8<--
(Then a welcome message is shown in <language>)

**Screenshots**
The generated name is "ThenWirdEineBegrUngAufEnglischAngezeigt". The two German characters 'ü' and 'ß' produce a single 'U'.

**Additional context**
 - XCode Version: 13.3.1
 - CucumberSwift Version: 3.3.6

**Comment by Tyler-Keith-Thompson** [comment]
Thanks! I've used CFStringTokenizer to be smarter about splitting by word even allowing for emojis. This means class name generation should be locale aware and allow for any range of acceptable characters.
