### ISSUE TITLE
Missing required module 'CucumberSwift_ObjC' in new swift UITest target

### ISSUE THREAD

**Issue by richardsimkins** [Tyler-Keith-Thompson/CucumberSwift#45]
**Describe the bug**
Compiler fails to build test target with the error "Missing required module 'CucumberSwift_ObjC'"

**To Reproduce**
1. I created a new UITest target.
2. I added the CucumberSwift package dependency to the project.
3. I included feature files in a reference folder "Features".
4. I created a swift file with the code in the screenshot.
5. I run the test target to start a build.
6. The build fails with the error.

**Expected behavior**
The build should succeed without error.

**Screenshots**
<img width="1073" alt="Screenshot 2022-05-18 at 14 58 16" src="https://user-images.githubusercontent.com/74411927/169083537-0701c069-876b-42dc-8023-2afb0f356ad7.png">
<img width="1114" alt="Screenshot 2022-05-18 at 16 13 33" src="https://user-images.githubusercontent.com/74411927/169083553-1bc456a9-cbac-4488-980c-7cc7ef0d6913.png">

**Additional context**
 - XCode Version: [e.g. XCode 13.3]
 - CucumberSwift Version: [e.g. 3.3.11]
 - Example Feature File (if applicable) N/A

**Comment by richardsimkins** [comment]
I have tried using the Cocoapod pod and it builds fine with no other change.

I would prefer to be using Swift Package Manager if possible since we have been looking to move away from using  Cocoapods.

**Comment by Tyler-Keith-Thompson** [comment]
I'll look into this more as soon as I can. This weekend I'll be up on a mountain with no internet access.

Just in case it's something with your local environment can you clear your package cache? The Objective-C target is a transitive dependency so it should be there.

Does the [sample repo](https://github.com/Tyler-Keith-Thompson/CucumberSwiftSample/blob/main/SwiftPackageManager/README.md) work for you?

I'll look into this when I can, but some of that might help in the meantime

**Comment by richardsimkins** [comment]
Thanks for the quick reply. I'll try what you suggest and get back to you. Enjoy your mountain climb.

**Comment by Tyler-Keith-Thompson** [comment]
Did any of those things work? I was not able to reproduce this problem using the sample app.

**Comment by richardsimkins** [comment]
Sorry for the delay in getting back to you.

The issue I was having was I had linked the library to the app's target and not the test target.

Thanks for your help.
