### ISSUE TITLE
Display Scenario name in test run results

### ISSUE THREAD

**Issue by jmruzik87** [Tyler-Keith-Thompson/CucumberSwift#5]
**Is your feature request related to a problem? Please describe.**
No problem, just a new feature.

**Describe the solution you'd like**
When I look into test failures to start diagnosing an issue with my project, it would be useful to see the Scenario name tacked on to the Steps that have failed in a test.  Something along the lines of this would be incredible, but really any solution would be great:

Failing tests:
AwesomeCucumberTests:
-[Scenario ElementsAreAddedCorrectly] -[Step andIAmShownOnlyElements]
-[Scenario ElementsAreRemovedCorrectly] -[Step andIAmShownOnlyElements]

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Tyler-Keith-Thompson** [comment]
Much as I am loathed to admit defeat Apple simply doesn't give the control necessary (or if they do it's entirely undocumented) for this feature request to happen. I'll keep an eye out for changes, but for now you can at least see the generated JSON report which showcases which steps failed. You can also use a tool like https://www.npmjs.com/package/cucumber-html-reporter  to parse this into a nifty little html artifact.
