### ISSUE TITLE
Cucumber Expressions containing plain texts are mismatched

### ISSUE THREAD

**Issue by hkingverily** [Tyler-Keith-Thompson/CucumberSwift#52]
**Describe the bug**
Cucumber Expressions containing plain texts are mismatched

**To Reproduce**
Codes to reproduce the behavior:

Feature file:
    Given the member has A
    And the member has B
    And the member has C

CucumberSwift code:
      Given("the member has A" as CucumberExpression) { _, _ in
        print("Print the member has A")
      }
      Given("the member has B" as CucumberExpression) { _, _ in
        print("Print the member has B")
      }
      Given("the member has C" as CucumberExpression) { _, _ in
        print("Print the member has C")
      }

**Expected output**
...
Print the member has A
...
Print the member has B
...
Print the member has C
...

**Actual output**
...
    t =    26.88s Given the member has A
Print the member has C
...
    t =     0.03s Given the member has B
Print the member has C
...
    t =     0.03s Given the member has C
Print the member has C
...

**Additional context**
 - XCode Version: 13.4.1
 - CucumberSwift Version: 3.3.20

**Comment by Tyler-Keith-Thompson** [comment]
Well that's an embarrassing oversight. The expressions library was assuming matches if there weren't any parameters found. I'll have this fixed shortly.

Good catch, thanks!

**Comment by Tyler-Keith-Thompson** [comment]
Alright, CucumberSwiftExpressions v0.0.8 fixes this. If you're using CocoaPods you can run `pod update CucumberSwiftExpressions` or if. you're using SPM you can update your packages. I'm also releasing a new version of CucumberSwift that declares v0.0.8 as a minimum version for CucumberSwiftExpressions.
