### ISSUE TITLE
Error Could't load project at: ....

### ISSUE THREAD

**Issue by uo9qsuf** [Tyler-Keith-Thompson/CucumberSwift#55]
Tests throw always Couldn't load project at: ... error

/Users/user/Library/Developer/Xcode/DerivedData/CucumberSwiftSample-gkijucsclvpfxlaonviycrdrenry/SourcePackages/checkouts/CucumberSwift/Sources/CucumberSwift/Gherkin/XCode-Specific Couldn't load project at: /Users/user/Library/Developer/Xcode/DerivedData/CucumberSwiftSample-gkijucsclvpfxlaonviycrdrenry/SourcePackages/checkouts/CucumberSwift/Sources/CucumberSwift/Gherkin/XCode-Specific

**To Reproduce**
1. Download the exmaple App
2. change the package version in the Swift Package manager from 3.1.1 to 3.0.0
3. run the tests

**Expected behavior**
No error and the tests should run like under version 3.1.1

**Additional context**
 - XCode Version: 14.1
 - CucumberSwift Version: 3.3.22

**Comment by Tyler-Keith-Thompson** [comment]
This is because my automated versioning script always bumps the patch version. So there is no tag for 3.0.0, the earliest 3.x version is 3.0.1.

Were you attempting to pin to all 3.x versions when you discovered this? Or is there another use case to support?

I admittedly haven't revisited my versioning scripts since before SPM support

**Comment by uo9qsuf** [comment]
@Tyler-Keith-Thompson  my use case was only to have the newset one :-)

**Comment by DerFlash** [comment]
Unfortunately we still have this problem.

I switched the SPM dependency to exact 3.3.22, then to up to next major from 3.3.22, also to "branch main". It doesn't matter.
I removed derived data and even the ~/Library/Caches/org.swift.swiftpm and restarted Xcode, nothing helped.

Overall everything related to CucumberSwifts' functionality works fine. It's just that Xcode cannot list the folders content:
<img width="559" alt="Bildschirm­foto 2022-12-02 um 12 55 39" src="https://user-images.githubusercontent.com/185013/205287578-a8839296-233f-4e87-94e2-d7978e66367b.png">

And it always shows the said error which confuses our developers.
The error isn't even listed in the report navigators build step. Just in Xcodes top bar and the issue navigator. 🤷

**Comment by mccarron** [comment]
We're seeing the exact same problem as @DerFlash and started seeing it with the newer Xcode 14 builds, maybe was it 14.1?

**Comment by Tyler-Keith-Thompson** [comment]
Well this is apparently quite serious. Seems like Apple may have broken something out from under me. 

I will work on this ASAP, but I have a day job so it may not happen today.

**Comment by DerFlash** [comment]
Sure thing, hope you had a lovely weekend!
Thanks a lot for the quick response and your great work here!

**Comment by Tyler-Keith-Thompson** [comment]
Thank you for that gentle reminder. My weekend was 100% taken over by said day job. That said, I have a fix out. It required me to clear derived data, but CucumberSwift 3.3.23 does not throw that error (verified in the Sample app)

I am going to leave this issue open for a while just in case anybody else runs into issues that I'm no longer seeing.

**Comment by mccarron** [comment]
@Tyler-Keith-Thompson that fix worked great, thanks again for that!

**Comment by DerFlash** [comment]
Works like a charm. Problem's gone! Thanks a lot again!
