### ISSUE TITLE
Need help with setting up CucumberSwift

### ISSUE THREAD

**Issue by badrinrs** [Tyler-Keith-Thompson/CucumberSwift#62]
I have the project setup as below:

![Screenshot 2023-01-11 at 11 17 21 AM](https://user-images.githubusercontent.com/6345184/211897762-5f0b40aa-f147-4031-a223-5b99cd2601f3.png)

When trying to Run CucumberSwiftTestAppUITest, I am not getting any errors although none of the steps are defined. Also, I do not see the test method `testGherkin()` in the tests navigator.

Also, I see a warning/error in xcode: 
`/Users/bsathya/Library/Developer/Xcode/DerivedData/CucumberSwiftTestApp-dxhvqbfgfivuqrdpomludwbgwqlx/SourcePackages/checkouts/CucumberSwift/Sources/CucumberSwift/Gherkin/XCode-Specific Couldn't load project at: /Users/bsathya/Library/Developer/Xcode/DerivedData/CucumberSwiftTestApp-dxhvqbfgfivuqrdpomludwbgwqlx/SourcePackages/checkouts/CucumberSwift/Sources/CucumberSwift/Gherkin/XCode-Specific`

**Comment by Tyler-Keith-Thompson** [comment]
Did you get this working? It looked like you were on an older version of CucumberSwift

**Comment by uo9qsuf** [comment]
@Tyler-Keith-Thompson Yes it works, but the error don't disappear.

This is my working account my prvate is @bitsmakerde ;-)
