### ISSUE TITLE
Stub generation uses deprecated Matcher initializer

### ISSUE THREAD

**Issue by DevMobileAS** [Tyler-Keith-Thompson/CucumberSwift#68]
**Describe the bug**
With a .feature line like this:
"Angenommen ich starte die App frisch"

... the automatic step generation actually generates stubs like this:
Given("^ich starte die App frisch$") ...

This creates the following warning:
'init(_:callback:line:file:)' is deprecated: To use regular expressions with CucumberSwift please migrate to use regex literals.

**Expected behavior**
Looking at the Matcher, the best matching code would be like:
Given(/^ich starte die App frisch$/) ...

→ I'll create a pull request for this in a seconds.

**Comment by Tyler-Keith-Thompson** [comment]
This is fixed in 4.0.4
