### ISSUE TITLE
BeforeFeature and BeforeScenario hooks are ignored for Scenario Outline

### ISSUE THREAD

**Issue by olyv** [Tyler-Keith-Thompson/CucumberSwift#7]
**Describe the bug**
BeforeFeature and BeforeScenario hooks are ignored for Scenario Outline

**To Reproduce**
1. Create feature file containing Scenario Outline
```
Feature: Minimal Scenario Outline

@123
Scenario Outline: minimalistic
Given the <what>

Examples:
| what       |
| minimalism |
```
2. Add BeforeFeature and BeforeScenario hooks
```
BeforeFeature { feature in
      print(feature.debugDescription)
 }
        
BeforeScenario { scenario in
      print(scenario.debugDescription)
}
```
3. Execute tests

**Expected behavior**
BeforeFeature and BeforeScenario hooks are executed printing appropriate debugDescription of each entity

**Actual behavior**
BeforeFeature and BeforeScenario hooks are omitted 

**Additional context**
 - XCode Version: XCode 10.2.1
 - CucumberSwift Version: 2.2.3

Please note that BeforeStep hook is still executed

**Comment by Tyler-Keith-Thompson** [comment]
Alright, I've got a test in place that reproduces the issue.

**Comment by Tyler-Keith-Thompson** [comment]
V2.2.4 should fix your issue!

Brief explanation of what happened:

A lot of logic is done at the step level and depends on a parent/child relationship, steps know about the scenario they are contained in, scenario know about the features they are contained in. When you add hooks it actually starts at the step level (as steps are the actual tests), then works its way up the hierarchy to determine whether the hook should fire.

Moral is for Scenario Outlines while the generated scenarios had a parent of the feature, the steps didn't have parents and thus some pieces of functionality were lost. Letting the steps know which scenario they belong to fixed the hooks.

**Comment by olyv** [comment]
Awesome! That was really fast fix, thank you. I just updated CucumberSwift to 2.2.6 and hooks are executed as expected. And yes -- Cucumber AST is kind of really twisted.

Offtopic: I tried to clone CucumberSwift project in order to make some troubleshooting on my own but I couldn't open it Xcode 10.2.1, Xcode only endlessly displayed 'Opening...'. Does require some more patience or any other setup is required in order to get the project? I am new to Swift and Xcode, so I can miss something really obvious.

**Comment by Tyler-Keith-Thompson** [comment]
Hrm, shouldn't be anything special required. I had a workspace in there that I never cleaned up, so make sure to open the project and not the workspace.

Other than that seems like your Xcode was misbehaving, welcome to the start of a long journey Xcode misbehaving a lot.

On a whim try running an `xcode-select --install` from your command line before opening Xcode.
