### ISSUE TITLE
Scenarios are running 2 times

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [Tyler-Keith-Thompson/CucumberSwift#88]
Is there any reason, why should my scenarios run two times? I cannot find any settings for this. They even run two times when they are successful.

_Originally posted by @SurglogsGithubUser in https://github.com/Tyler-Keith-Thompson/CucumberSwift/discussions/85_

**Comment by Tyler-Keith-Thompson** [comment]
Not able to repro: https://github.com/Tyler-Keith-Thompson/CucumberSwift/discussions/85#discussioncomment-5763839

Suspect that perhaps the new way we show tests from #72 is just confusing folks who use the test navigator rather than the report navigator.

**Comment by MarekSlaninka** [comment]
Hi, sadly no, they actually run two times. I will try to debug the code and find the reason why that is.

**Comment by MarekSlaninka** [comment]
Even `override public class var defaultTestSuite: XCTestSuite` in `open class CucumberTest: XCTestCase` is called two times.  Do You have any idea, why that might be? Thank You

**Comment by MarekSlaninka** [comment]
Hi, I just want to remind myself with this issue. Do You have any idea why this might be?

**Comment by Tyler-Keith-Thompson** [comment]
Apologies, I haven't been able to repro and I haven't had much time to dedicate to this project. I expect things will ease up in a few weeks.

**Comment by MarekSlaninka** [comment]
Hi, I managed to check, if test is running second time and stop it then.


```
open class CucumberTest: XCTestCase {
    static var didRun = false
    
    open override func invokeTest() {
        guard !Self.didRun else {return}
        Self.didRun = true
        super.invokeTest()
    }
 ...
```

**Comment by Tyler-Keith-Thompson** [comment]
I'm glad you have a workaround! It's *very* weird that that's necessary. This is actually quite insightful, because it means that XCTest is picking up on the entire test case twice, (as opposed to tests accidentally running themselves repeatedly, or something).

**Comment by ianhlavats** [comment]
@Tyler-Keith-Thompson can you please review my PR #101 ?

**Comment by ianhlavats** [comment]
@Tyler-Keith-Thompson can we close this issue now?

**Comment by MarekSlaninka** [comment]
Yes, thank You
