### ISSUE TITLE
Couldn't load project from derived data

### ISSUE THREAD

**Issue by noureen-motorway** [Tyler-Keith-Thompson/CucumberSwift#90]
**Describe the bug**
I am trying to use this library in my project and adding the dependency via SPM. As soon as I add it, I starts getting a weird error and no matter if I clear the build, its just keep appearing.

**To Reproduce**
Just add the dependency via SPM into UI Test target

**Expected behavior**
I want to get rid of this error so that I can continue with this framework.

**Screenshots**
Screen shot is attached.
<img width="679" alt="Screenshot 2023-05-31 at 17 55 24" src="https://github.com/Tyler-Keith-Thompson/CucumberSwift/assets/129753831/78723dc5-d11c-489a-87bd-086990571c19">

**Additional context**
 - XCode Version: [e.g. XCode 14.3]
 - CucumberSwift Version: [e.g. 4.2.2]

**Comment by noureen-motorway** [comment]
@Tyler-Keith-Thompson  can you comment on that please?

**Comment by Tyler-Keith-Thompson** [comment]
I'll look into this ASAP. I really thought I removed that folder from SPM once Xcode 14 came out and caused problems. Don't expect much before the weekend, though.

**Comment by Tyler-Keith-Thompson** [comment]
4.3.1 should solve this once and for all!

**Comment by noureen-motorway** [comment]
@Tyler-Keith-Thompson : The original issue is gone but now after using the 4.3.1, I am getting another compiler error.
<img width="873" alt="Screenshot 2023-06-04 at 17 56 29" src="https://github.com/Tyler-Keith-Thompson/CucumberSwift/assets/129753831/50b0ae42-ef51-469c-9562-41fa3f80fde3">
I did try to install via carthage but getting the similar type of error.
<img width="610" alt="Screenshot 2023-06-04 at 17 53 52" src="https://github.com/Tyler-Keith-Thompson/CucumberSwift/assets/129753831/ead68245-c94c-4292-b786-501c427e4f61">

Any thoughts?

**Comment by Tyler-Keith-Thompson** [comment]
Wow...that's new. Okay so I know you're using Xcode 14.3 but what version of Swift and what version of the OS are your tests running on? (iOS/macOS/tvOS/whatever) are you using?

It's possible that there's some kind of async/await issue at play here, but that's supposed to be quite backwards compatible.

**Comment by Tyler-Keith-Thompson** [comment]
Carthage not working there is a bit different. That's just an ARM vs x86 thing which presumably you can fix by changing your Carthage command and/or version of Carthage. But that SPM error is odd

**Comment by noureen-motorway** [comment]
@Tyler-Keith-Thompson : for SPM I am using swift language version 5 and running my tests on iphone 14(16.4).
