### ISSUE TITLE
CucumberSwift doesn't compile with Xcode 15.3

### ISSUE THREAD

**Issue by stremsdoerfer** [Tyler-Keith-Thompson/CucumberSwift#98]
**Describe the bug**
When trying to build with Xcode 15.3. I get the following error in [CucumberTest](https://github.com/Tyler-Keith-Thompson/CucumberSwift/blob/5226892807bf773d8a4c45708eaf6fcaba62f612/Sources/CucumberSwift/Runner/CucumberTest.swift#L84): 
```
'addTeardownBlock' is only available in iOS 13.0 or newer
```

**To Reproduce**
1. Download zip of the project
2. Open CucumberSwift.xcodeproj with Xcode 15.3
3. Cmd + B

**Expected behavior**
Project should build correctly.

**Screenshots**

**Additional context**
 - Xcode Version: 15.3
 - Tried on latest CucumberSwift [commit](https://github.com/Tyler-Keith-Thompson/CucumberSwift/commit/5226892807bf773d8a4c45708eaf6fcaba62f612)
 - macOS Sonoma 14.4

**Comment by Tyler-Keith-Thompson** [comment]
I'll try to take a look, but my schedule is insane. Out of curiosity are you trying to build with just an ancient version of iOS? Or is this some bizarre eccentricity that only exists on Xcode 15.3?

**Comment by stremsdoerfer** [comment]
Nope, trying to build on iOS 17.4. 
Not sure why it pops up only now, since the library is iOS 10+. It doesn't look like anything is stopping this code from being called on that version.
Happy to push a PR, if you feel like the answer may be to raise the minimum version or if you see a quick alternative.

**Comment by Tyler-Keith-Thompson** [comment]
How bizarre....they either rewrote part of XCTest in Swift or added a Swift interface in 15.3. It used to be an ObjC method which doesn't have availability. God only knows why they chose iOS 13 as a minimum.

**Comment by Tyler-Keith-Thompson** [comment]
5.0.1 should fix this by raising minimum versions since I didn't want to figure out how to get clever enough to call the old ObjC versions.

I'm gonna close this issue now because it should work, but please feel free to comment if something doesn't work.
